-- GWAP Cloudflare Core V1
-- Minimal conversion intelligence schema.
-- Apply only after preview deployment is verified.

create table if not exists public.gwap_scanner_runs (
  id uuid primary key,
  session_id text,
  goal text not null,
  asset text not null,
  constraint text not null,
  move_key text not null,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gwap_scanner_runs_created_at_idx
  on public.gwap_scanner_runs (created_at desc);

create index if not exists gwap_scanner_runs_move_key_idx
  on public.gwap_scanner_runs (move_key);

create table if not exists public.gwap_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gwap_events_created_at_idx
  on public.gwap_events (created_at desc);

create index if not exists gwap_events_name_idx
  on public.gwap_events (event_name);

-- Service-role writes are performed server-side by the Cloudflare Worker.
-- Keep anon/client access closed until a separate customer-facing policy is required.
alter table public.gwap_scanner_runs enable row level security;
alter table public.gwap_events enable row level security;
